FROM node:22-slim

WORKDIR /blokmap-docs

COPY package.json package-lock.json ./

RUN npm install -g npm
RUN npm install

COPY . .

RUN npm run docs:build

CMD cp -r ./docs/.vitepress/dist/* "${OUTPUT_DIR:-/well-known}/"
